# Generated by Django 3.0.3 on 2020-02-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dealerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gst_number', models.IntegerField()),
                ('personal_email', models.EmailField(max_length=254)),
                ('company_email', models.EmailField(max_length=254)),
                ('personal_phone', models.IntegerField()),
                ('organization_phone', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('about', models.TextField()),
            ],
        ),
    ]
